server:
    port: 9090
    servlet:
        context-path: /board
        encoding:
            charset: UTF-8
            enabled: true
            force: true

spring:
    application:
        name: board
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/user
        username: root
        password: 2004

mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true

# hikari pool log
logging:
    level:
        org.hibernate.SQL: info
        root: info
        com.zaxxer.hikari.pool.HikariPool: debug